apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-rolebinding-22790
subjects:
  - kind: ServiceAccount
    name: webapp-sa-22790
roleRef:
  kind: Role
  name: webapp-role-22790
  apiGroup: rbac.authorization.k8s.io