apiVersion: apps/v1
kind: Deployment
metadata:
  name: 22790myapp
  namespace: 22790-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: 22790myapp
        image: jennixavier/helloworld:v1  # Replace with your actual backend image name
        ports:
            - containerPort: 80
          env:
            - name: APP_KEY 
              valueFrom:
                secretKeyRef:
                  name: webapp-secret-22790
                  key: APP_KEY
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: webapp-config-22790
                  key: WELCOME_MSG
