apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-role-16751
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
