apiVersion: apps/v1
kind: Deployment
metadata:
  name: 16751-webapp-deployment
  namespace: 16751-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: 16751-webapp-deployment
        image: davidhtcmail/todaycluster:v1  # Replace with your actual backend image name
        ports:
        - containerPort: 8001
        env:
            - name: APP_KEY 
              valueFrom:
                secretKeyRef:
                  name: webapp-secret-16751 - secret anem
                  key: APP_KEY  - under data -- value
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: webapp-config-16751
                  key: WELCOME_MSG

